{% set name = "umock-c" %}
{% set version = "2020.03.27" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  - url: https://github.com/Azure/umock-c/archive/1f0e52e3f54bdeeb138d400ea11701a1f7dc5e5c.zip
    sha256: 8be1cbfa2259ca1140d186154d2561d1ed76ab0b5ce4efef1db1371fd3d92343

build:
  number: 1
  run_exports:
    - {{ pin_subpackage(name, exact='x.x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make   # [not win]
    - ninja  # [win]
  host:
    - azure-macro-utils-c <2020.10.29
  run:
    - azure-macro-utils-c <2020.10.29

test:
  commands:
    - if not exist %PREFIX%\\Library\\include\\umock_c\\umock_c.h exit 1  # [win]
    - test -f "${PREFIX}/include/umock_c/umock_c.h"  # [not win]

about:
  home: https://github.com/Azure/umock-c
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: |
    A pure C mocking library

extra:
  recipe-maintainers:
    - xylar
    - seanyen
